services:
  backend:
    container_name: go-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
    - ./server:/app
    ports:
    - "8080:8080"
    networks:
    - app_network
  
  ml-service:
    container_name: python-ml
    command: tail -f /dev/null
    build:
      context: ./ml
      dockerfile: Dockerfile
    volumes:
    - ./ml:/app
    ports:
    - "8501:8501"
    networks:
    - app_network

  db:
    image: mysql
    container_name: mysql-db
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - app_network
  
networks:
    app_network:
      driver: bridge

volumes:
  db_data: