services:
  backend:
    container_name: go-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
    - "8080:8080"
    networks:
    - app_network
    environment: # DB接続情報などの環境変数を設定(.envファイルからロードされる)
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}
    depends_on:
      db:
        condition: service_healthy
  
  ml-service:
    container_name: python-ml
    command: tail -f /dev/null
    build:
      context: ./ml
      dockerfile: Dockerfile
    volumes:
    - ./ml:/app
    ports:
    - "8501:8501"
    networks:
    - app_network

  db:
    image: mysql
    container_name: mysql-db
    build: 
      context: ./db
      dockerfile: Dockerfile
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - app_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck: # 起動を待つためのヘルスチェック
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 5s
      timeout: 3s
      retries: 5

# サービス間で通信するためのカスタムネットワークを定義
networks:
    app_network:
      driver: bridge

# Dockerボリュームを定義し、データベースのデータを永続化
volumes:
  db_data: