apiVersion: apps/v1
kind: Deployment
metadata:
  name: aminavi-deployment
  labels:
    app: aminavi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aminavi
  template:
    metadata:
      labels:
        app: aminavi
    spec:
      containers:
        - name: go-backend
          image: assam5649/go-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-env
          volumeMounts:
            - name: firebase-json-volume
              mountPath: /app/firebase.json
              subPath: firebase.json
            - name: gcs-json-volume
              mountPath: /app/gcs-owner.json
              subPath: gcs-owner.json
            - name: gcs-json-volume
              mountPath: /app/gcs.json
              subPath: gcs.json

        - name: python-ml
          image: assam5649/python-ml:latest
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: app-env

        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: DB_PASS
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

