apiVersion: apps/v1
kind: Deployment
metadata:
  name: aminavi-deployment
  labels:
    app: aminavi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aminavi
  template:
    metadata:
      labels:
        app: aminavi
    spec:
      containers:
        - name: go-backend
          image: yourdockerhubuser/go-backend:<commit_SHA>
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-env
          volumeMounts:
            - name: firebase-json-volume
              mountPath: /app/firebase.json
              subPath: firebase.json
            - name: gcs-json-volume
              mountPath: /app/gcs-owner.json
              subPath: gcs-owner.json
            - name: gcs-json-volume
              mountPath: /app/gcs.json
              subPath: gcs.json

        - name: python-ml
          image: yourdockerhubuser/python-ml:<commit_SHA>
          ports:
            - containerPort: 8501

        - name: mysql
          image: mysql:latest
          envFrom:
            - secretRef:
                name: app-env
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: firebase-json-volume
          secret:
            secretName: firebase-json
        - name: gcs-json-volume
          secret:
            secretName: gcs-secrets
        - name: mysql-data
          emptyDir: {}
