apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
spec:
  type: NodePort
  selector:
    app: aminavi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: python-ml-service
spec:
  type: NodePort
  selector:
    app: aminavi
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30801

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: aminavi
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
