name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: AmiNavi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build & Push Go Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-backend:${COMMIT_SHA} \
                       -t ${{ secrets.DOCKER_USERNAME }}/go-backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/go-backend:${COMMIT_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/go-backend:latest

      - name: Build & Push Python ML
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-ml:${COMMIT_SHA} \
                       -t ${{ secrets.DOCKER_USERNAME }}/python-ml:latest ./ml
          docker push ${{ secrets.DOCKER_USERNAME }}/python-ml:${COMMIT_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/python-ml:latest
