# .github/workflows/ci.yml

name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Set up MySQL User
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "CREATE USER 'testuser'@'%' IDENTIFIED BY 'testpass';"
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'%';"
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "FLUSH PRIVILEGES;"
        env:
          MYSQL_ROOT_PASSWORD: password
          DB_HOST: 127.0.0.1
          DB_PORT: 3306

      - name: Run tests
        run: |
          cd server
          go test ./test/...
        env:
          DB_USER: testuser
          DB_PASS: testpass
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: testdb