# .github/workflows/test.yml
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=6
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: |
          cd server
          go test ./...  # or specific test path
        env:
          DB_USER: testuser
          DB_PASS: testpass
          DB_HOST: db
          DB_PORT: 3306
          DB_NAME: testdb
          MYSQL_ROOT_PASSWORD: password
